apiVersion: v1
kind: Service
metadata:
        name: python-service
        labels:
                name: server-service
                app: server #posto mi se container zove server
spec:
        type: LoadBalancer
        ports:
                port: 8081
                targetPort: 8081
        containers:
               name: server
               image: server:1
               ports:
                       containerPort: 8081
